services:
  # Frontend - Static Site
  - type: web
    name: campusia-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
